### ISSUE TITLE
Getting Error on yarn run generate

### ISSUE THREAD

**Issue by drupalshift** [clarkdo/hare#27]
Hi there 

When i run `yarn run generate` i get this error for each route : 

```
Route: '/'
TypeError: Cannot read property 'headers' of undefined at Negotiator.languages
```
Any other command works fine but generate

**Comment by clarkdo** [comment]
The error in `generate` will be fixed in #28 
ERROR reason: Per [nuxt doc](https://nuxtjs.org/guide/commands/#static-generated-deployment) : 
* When generating your web application with nuxt generate, the context given to data() and fetch() will not have req and res.
Note: it still will get error when only deploy the static files and no the backend api (such as login ,menus)
