### ISSUE TITLE
Document how to use

### ISSUE THREAD

**Issue by renoirb** [clarkdo/hare#275]
Hi, this looks promising and this got my attention because it is said being an application boilerplate.

I've tried to run in development, but I cannot see how to setup.

Is there a document about using it?

**Comment by clarkdo** [comment]
Sorry for the late reply.

For now, you can simply refer to [README.md](https://github.com/clarkdo/hare/blob/dev/README.md) 😸 

Because this repo is a boilerplate based on Nuxt, so you can also read the [Nuxt site](https://nuxtjs.org/) to get knowledge.

If you have any problem in using this repo, you can also feel free to open issue in this repo, I will try my best to help you.

And I will try to add more documentations asap, thank you for your effective issue.

**Comment by renoirb** [comment]
Hi, no problem about the delay.
I've spent more time reading around the stack, all I needed to learn was indeed out there on the respective sites: Nuxt, Vue-Meta, VueX, etc.

My concern was mostly about how to use as-is, but I needed to chew the documentation first and I've come to realise all the  moving parts.

Thanks for publishing this project, it turned out to be quite an educative source-code read tutorial.
